version: '3.8'

services:

  backend:

    build:
      context: ./backend

    ports:
      - "5000:5000"


    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules


    environment:
      - NODE_ENV=production


    networks:
      - app-network

  # Frontend Service
  frontend:

    build:
      context: ./frontend


    ports:
      - "3000:3000"


    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules


    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider


    depends_on:
      - backend


    networks:
      - app-network

volumes:

  backend_node_modules:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge
